### ISSUE TITLE
Předávání instance User napříč aktivitami

### ISSUE THREAD

**Issue by Relickus** [thepetas/shiftify#14]
V různých situacích je třeba si jednu instanci User předávat do dalších aktivit. Běžný Intent neumožnuje poslat aktivitě celou třídu -> nyní je to řešeno tak, že se v každé aktivitě znovu vyhledá User pomocí předaného userId. 
Je to neefektivní. Je třeba vyřešit předávání instance User napříč aktivitami.

**Comment by thepetas** [comment]
V tom případě by třída User musela implementovat rozhraní Parcelabel.

**Comment by Relickus** [comment]
Jj o tom jsem přesně četl, proto jsem vytvořil ten issue, abysme to zvážili, jestli to za tu efektivitu stojí předělávat.
