### ISSUE TITLE
Vytvoření layoutů všech obrazovek

### ISSUE THREAD

**Issue by Relickus** [thepetas/shiftify#6]
## Aktivity k vytvoření:

- [x]  Editace osoby
- [x] Rozvrh směn na zadaný den (fragment)
- [x]  O projektu (fragment)
- [x]  Vytvoření osoby 
- [x]  Seznam osob (fragment)
---------------------------
## Nerozhodnuté:
- [ ]  Zpětná vazba 
- [ ]  Zrušení směny

**Comment by jenkys** [comment]
@Relickus 

Ahoj, 

už jsem psal email - prosím o odkaz, kde si můžu layouty prohlídnout - nejlépe, kdybyste vždy evidovali odkazy v rámci issues, ve kterých úkol zpracováváte. Poté také do dokumentace projektu.

Díky
